### ISSUE TITLE
chat.postMessage checkResponse() failed "invalid_arguments"

### ISSUE THREAD

**Issue by LinuxRocks2000** [coin-au-carre/slacking#11]
Why is this error happening? Do I need to add something else?
My code:
```c++
#include <slacking/slacking.hpp>
#define TEST
#include "secret.h"

int main(){
    auto& slack = slack::create(SECRET);
    slack.chat.channel="#general";
    slack.chat.postMessage("Ding dong man, ding dong. Ding dong, yo, ding dong.");
    return 0;
}

```

**Comment by avpcan** [comment]
I was getting this, too. I tried editing the slacking.hpp to be in verbose mode and found that this is the error:
`{"deprecated_argument":"as_user","error":"invalid_arguments","ok":false}`

The error is because [slack deprecated the use of as_user for chat.postMessage for new slack apps](https://api.slack.com/authentication/quickstart#perspective).

In my case, I actually wanted to use webhooks ( [Here's how to set up a webhook](https://api.slack.com/messaging/webhooks) )
With webhooks, [this is the example](https://github.com/coin-au-carre/slacking/blob/master/examples/07-webhook.cpp) to base your code on, and this approach is working for me.

**Comment by coin-au-carre** [comment]
Hello, thanks for the issue and the workaround. 
I will try to work on an update for  Slacking :).

**Comment by coin-au-carre** [comment]
This PR should fix the issue and you will be able to use postMessage as before !

https://github.com/coin-au-carre/slacking/pull/12

Indeed, the "as_user" is now deprecated, I just removed it from slacking.hpp.

**Comment by coin-au-carre** [comment]
And sorry for the late reply guys!
